---
- hosts: splunk
  become: true
  vars:
    splunk_rpm_url: "https://download.splunk.com/products/splunk/releases/10.0.2/linux/splunk-10.0.2-e2d18b4767e9.x86_64.rpm"
    splunk_username: ""  # Set your Splunk download username (if needed)
    splunk_password: ""  # Set your Splunk download password (if needed)
  tasks:
    - name: Gather EC2 instance facts
      ec2_metadata_facts:

    - name: Update system
      yum:
        name: '*'
        state: latest

    - name: Install wget
      yum:
        name: wget
        state: present

    - name: Download Splunk RPM
      get_url:
        url: "{{ splunk_rpm_url }}"
        dest: /tmp/splunk.rpm
        username: "{{ splunk_username }}"
        password: "{{ splunk_password }}"

    - name: Install Splunk
      yum:
        name: /tmp/splunk.rpm
        state: present

    - name: Enable Splunk to start on boot
      command: /opt/splunk/bin/splunk enable boot-start -user splunk

    - name: Start Splunk service
      command: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt
      become_user: splunk
      ignore_errors: true  # In case it's already started