---
- name: Verify Splunk Service
  hosts: all
  become: true

  tasks:
    - name: Check if Splunk service is running
      ansible.builtin.shell: /opt/splunk/bin/splunk status
      register: splunk_status
      failed_when: "'splunkd is running' not in splunk_status.stdout"

    - name: Wait for Splunk Web (Port 8000) to be reachable
      ansible.builtin.wait_for:
        port: 8000
        delay: 5
        timeout: 30
        msg: "Splunk Web Interface is not responding on port 8000"

        